spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Minispace;encrypt=true;trustServerCertificate=true
    username: sa
    password: reB@jKs*X9
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

