spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: password
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange:
      notification: notifications
    queue:
      notification:
        cmd: notification-cmd-queue
        evt: notification-evt-queue
    routing-key:
      notification:
        cmd: notification-cmd-register
        evt: notification-evt
  amqp:
    deserialization:
      trust:
        all: true

application:
  smtp:
    application:
      name: MiniSpace
      password: eblu ccyb btet uhjb
    mail: minispaceorganization@gmail.com
    password:
  scheduler:
    notifications: 0/10 * * * * *
